"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Download, FileUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { importSourceRecords } from "../research-actions";
export function LibraryTools() { const t = useTranslations("wiki"); const router = useRouter(); const fileInput = useRef<HTMLInputElement>(null); const [open,setOpen]=useState(false); const [records,setRecords]=useState<unknown[]>([]); const [name,setName]=useState(""); const [pending,setPending]=useState(false); const [message,setMessage]=useState(""); async function preview(file: File) { setPending(true); const data=new FormData(); data.set("file",file); const response=await fetch("/api/wiki/import",{method:"POST",body:data}); const body=await response.json(); if(response.ok){setRecords(body.records);setName(file.name);setOpen(true);} else setMessage(body.error); setPending(false); } return <div className="flex flex-wrap gap-2"><input hidden ref={fileInput} type="file" accept=".bib,.bibtex,.ris" onChange={(event)=>{const file=event.target.files?.[0];if(file)void preview(file);event.target.value="";}}/><Button variant="outline" onClick={()=>fileInput.current?.click()} disabled={pending}><FileUp className="size-4" />{t("importLibrary")}</Button><Button variant="outline" nativeButton={false} render={<a href="/api/wiki/export?format=bibtex" />}><Download className="size-4" />BibTeX</Button><Button variant="outline" nativeButton={false} render={<a href="/api/wiki/export?format=ris" />}><Download className="size-4" />RIS</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{t("reviewImport")}</DialogTitle></DialogHeader><p className="text-sm">{t("importPreview",{name,count:records.length})}</p>{message&&<p className="text-sm text-muted-foreground">{message}</p>}<div className="max-h-64 divide-y overflow-y-auto rounded border">{records.slice(0,100).map((record,index)=><p key={index} className="p-2 text-sm">{(record as {title?:string}).title}</p>)}</div><Button disabled={!records.length||pending} onClick={async()=>{setPending(true);const result=await importSourceRecords(records);setMessage(t("importComplete",result));setPending(false);router.refresh();}}>{t("importConfirmed")}</Button></DialogContent></Dialog></div>; }
